insert into public.artworks (
  slug,
  title,
  description,
  category,
  collection_id,
  tags,
  price,
  currency,
  dimensions,
  availability,
  featured,
  homepage_featured,
  published,
  sort_order,
  gradient_index
)
values
  (
    'void-currents-i',
    'Void Currents I',
    'Deep oceanic turbulence captured through algorithmic fluid simulation. Each wave represents data flowing through neural pathways of a dormant consciousness.',
    'Fluid Dynamics',
    (select id from public.collections where slug = 'fluid-dynamics'),
    array['fluid','algorithmic','oceanic'],
    8200,
    'USD',
    '48 x 60 in',
    'available',
    true,
    true,
    true,
    1,
    0
  ),
  (
    'nocturne-collapse',
    'Nocturne Collapse',
    'A meditation on entropy: the systematic unraveling of ordered systems into beautiful chaos. Shot during the darkest hour before dawn.',
    'Abstract',
    (select id from public.collections where slug = 'abstract'),
    array['entropy','night','chaos'],
    6400,
    'USD',
    '40 x 52 in',
    'available',
    false,
    true,
    true,
    2,
    1
  ),
  (
    'chromatic-tension',
    'Chromatic Tension',
    'Color as conflict. The violent meeting of warm and cold spectra, frozen at the moment of maximum contrast between desire and restraint.',
    'Chromatic',
    (select id from public.collections where slug = 'chromatic'),
    array['color','spectrum','contrast'],
    7300,
    'USD',
    '44 x 58 in',
    'reserved',
    false,
    true,
    true,
    3,
    2
  ),
  (
    'depth-sounding',
    'Depth Sounding',
    'Mapping the invisible layers beneath perception. What lies below the surface of awareness, under the still water of the mind?',
    'Fluid Dynamics',
    (select id from public.collections where slug = 'fluid-dynamics'),
    array['depth','perception','water'],
    5900,
    'USD',
    '36 x 50 in',
    'available',
    false,
    true,
    true,
    4,
    3
  ),
  (
    'signal-noise',
    'Signal / Noise',
    'The perpetual human struggle to extract meaning from the overwhelming background hum of a world drowning in its own data.',
    'Digital',
    null,
    array['signal','data','computation'],
    6800,
    'USD',
    '42 x 48 in',
    'available',
    false,
    true,
    true,
    5,
    4
  )
on conflict (slug) do nothing;
